"""
CQRS command handler for the ObjectMaskAnnotation3D task.

Pipeline
--------
1. Extract XYZ + colour arrays from the input point cloud.
2. Load image — either from ``image_input`` (bytes / file path) or by
   rendering a synthetic front-view image from the point cloud itself.
3. Resolve / download the YOLO11n-seg checkpoint.
4. Load and cache the YOLO model (thread-safe double-checked locking).
5. Run YOLO11n-seg inference → per-instance (bbox, mask, label, confidence).
6. Back-project all 3D points into 2D using camera intrinsics.
7. Vectorised mask lookup selects which points belong to each detected instance.
8. Optionally build per-object extracted clouds and/or an annotated full cloud.

Front-view synthesis (image_input=None)
---------------------------------------
When no image is provided the handler renders a synthetic RGB image by
projecting each point's XYZ into pixel coordinates and painting its colour.
Points are painted far-to-near so the nearest point wins at each pixel.
The canvas size is derived from the principal point: W = 2·cx+1, H = 2·cy+1.
For point clouds generated by DepthEstimation the result is pixel-for-pixel
identical to the original photo because each pixel has exactly one point.

Device support
--------------
CUDA, MPS (Apple Silicon), and CPU are auto-detected via ``_torch_device()``.
AMD/ROCm surfaces as ``cuda`` through PyTorch's ROCm-compatible CUDA API,
so it is supported automatically without any extra branch.
"""

from __future__ import annotations

import io
import threading

import numpy as np
from PIL import Image

from vizion3d.core.cqrs import CommandHandler

from ._geometry import (
    _backproject,
    _clone_cloud,
    _derive_intrinsics_from_cloud,
    _extract_cloud_arrays,
    _make_full_cloud,
    _make_sub_cloud,
    _render_front_view,
    _resolve_intrinsics,
)
from .commands import ObjectMaskAnnotation3DCommand
from .defaults import resolve_annotation_model_backend
from .models import MaskAnnotation3D, ObjectMaskAnnotation3DConfig, ObjectMaskAnnotation3DResult

__all__ = [
    "ObjectMaskAnnotation3DHandler",
    "_backproject",
    "_clone_cloud",
    "_derive_intrinsics_from_cloud",
    "_extract_cloud_arrays",
    "_make_full_cloud",
    "_make_sub_cloud",
    "_render_front_view",
    "_resolve_intrinsics",
]

_OBJECT_COLORS: list[list[float]] = [
    [1.0, 0.20, 0.20],
    [0.20, 1.0, 0.20],
    [0.20, 0.50, 1.0],
    [1.0, 0.90, 0.10],
    [1.0, 0.20, 1.0],
    [0.10, 1.0, 0.90],
    [1.0, 0.55, 0.10],
    [0.70, 0.10, 1.0],
    [0.10, 0.90, 0.50],
    [1.0, 0.40, 0.70],
    [0.50, 0.85, 0.20],
    [0.20, 0.50, 0.80],
]


class ObjectMaskAnnotation3DHandler(
    CommandHandler[ObjectMaskAnnotation3DCommand, ObjectMaskAnnotation3DResult]
):
    """Handles :class:`~vizion3d.annotation.commands.ObjectMaskAnnotation3DCommand`.

    YOLO11n-seg models are loaded on first use and cached in a class-level dict
    so subsequent calls within the same process reuse weights without re-reading
    disk.  A lock ensures thread-safe initialisation.
    """

    _annotation_models: dict = {}
    _model_lock = threading.Lock()

    def handle(self, command: ObjectMaskAnnotation3DCommand) -> ObjectMaskAnnotation3DResult:
        model_id = resolve_annotation_model_backend(command.model_backend)

        # Extract point cloud arrays first — needed for front-view synthesis
        # and for the back-projection step regardless of image source.
        pts, colors_orig = _extract_cloud_arrays(command.point_cloud)

        if command.image_input is None:
            # Intrinsics must be resolved before rendering (rendering requires them).
            # If any are None, derive consistent values from the cloud's angular extent.
            cfg = _derive_intrinsics_from_cloud(pts, command.advanced_config)
            image = _render_front_view(pts, colors_orig, cfg)
        elif isinstance(command.image_input, str):
            image = Image.open(command.image_input).convert("RGB")
            cfg = _resolve_intrinsics(command.advanced_config, *image.size)
        else:
            image = Image.open(io.BytesIO(command.image_input)).convert("RGB")
            cfg = _resolve_intrinsics(command.advanced_config, *image.size)

        img_w, img_h = image.size

        detections = self._run_yolo(model_id, image, cfg)
        detections = sorted(detections, key=lambda d: d[2], reverse=True)

        if not detections:
            annotated_cloud = None
            if command.return_annotated_cloud:
                import open3d as o3d

                annotated_cloud = _clone_cloud(command.point_cloud, o3d)
            return ObjectMaskAnnotation3DResult(
                annotations=[],
                annotated_cloud=annotated_cloud,
                backend_used=model_id,
            )

        in_bounds_idx, u_ib, v_ib = _backproject(pts, img_w, img_h, cfg)

        annotations: list[MaskAnnotation3D] = []
        colors_new = colors_orig.copy() if command.return_annotated_cloud else None

        for det_idx, det in enumerate(detections):
            label, class_id, confidence, bbox_2d, mask_hw = det

            in_mask = mask_hw[v_ib, u_ib]
            obj_pt_idx = in_bounds_idx[in_mask].tolist()
            obj_pt_coords = pts[obj_pt_idx].tolist()

            object_cloud = None
            if command.return_object_clouds and obj_pt_idx:
                import open3d as o3d

                object_cloud = _make_sub_cloud(pts, colors_orig, obj_pt_idx, o3d)

            if colors_new is not None and obj_pt_idx:
                col = _OBJECT_COLORS[det_idx % len(_OBJECT_COLORS)]
                colors_new[obj_pt_idx] = col

            annotations.append(
                MaskAnnotation3D(
                    label=label,
                    class_id=class_id,
                    confidence=confidence,
                    bbox_2d=bbox_2d,
                    mask_2d=mask_hw,
                    point_indices=obj_pt_idx,
                    point_coords=obj_pt_coords,
                    object_cloud=object_cloud,
                )
            )

        annotated_cloud = None
        if command.return_annotated_cloud:
            import open3d as o3d

            annotated_cloud = _make_full_cloud(pts, colors_new, o3d)

        return ObjectMaskAnnotation3DResult(
            annotations=annotations,
            annotated_cloud=annotated_cloud,
            backend_used=model_id,
        )

    # ── Model loading ─────────────────────────────────────────────────────────

    def _load_yolo(self, model_path: str):
        if model_path in self._annotation_models:
            return self._annotation_models[model_path]

        with self._model_lock:
            if model_path in self._annotation_models:
                return self._annotation_models[model_path]

            try:
                import torch
                from ultralytics import YOLO
            except ImportError as exc:
                raise ImportError(
                    "ObjectMaskAnnotation3D requires ultralytics. Run: pip install ultralytics"
                ) from exc

            device = self._torch_device(torch)
            model = YOLO(model_path)
            self._annotation_models[model_path] = (model, device)
            return self._annotation_models[model_path]

    # ── Inference ─────────────────────────────────────────────────────────────

    def _run_yolo(
        self,
        model_path: str,
        image: Image.Image,
        cfg: ObjectMaskAnnotation3DConfig,
    ) -> list[tuple[str, int, float, list[float], np.ndarray]]:
        model, device = self._load_yolo(model_path)

        results = model.predict(
            source=image,
            conf=cfg.conf_threshold,
            iou=cfg.iou_threshold,
            device=device,
            verbose=False,
            retina_masks=True,
        )

        result = results[0]

        if result.masks is None or result.boxes is None or len(result.boxes) == 0:
            return []

        boxes_xyxy = result.boxes.xyxy.cpu().numpy()
        classes = result.boxes.cls.cpu().numpy()
        confs = result.boxes.conf.cpu().numpy()
        masks_tensor = result.masks.data.cpu().numpy()  # (N, H, W) at original resolution

        detections = []
        for i in range(len(boxes_xyxy)):
            mask_hw = masks_tensor[i] > 0.5  # bool (H, W)
            detections.append(
                (
                    result.names[int(classes[i])],
                    int(classes[i]),
                    float(confs[i]),
                    boxes_xyxy[i].tolist(),
                    mask_hw,
                )
            )
        return detections

    # ── Pre-loading ───────────────────────────────────────────────────────────

    @classmethod
    def preload(cls, model_path: str) -> None:
        resolved = resolve_annotation_model_backend(model_path)
        cls()._load_yolo(resolved)

    # ── Device selection ──────────────────────────────────────────────────────

    @staticmethod
    def _torch_device(torch_module) -> str:
        if torch_module.cuda.is_available():
            return "cuda"
        if hasattr(torch_module.backends, "mps") and torch_module.backends.mps.is_available():
            return "mps"
        return "cpu"
