"""
CQRS command handler for the ObjectMaskAnnotation3D task.

Pipeline
--------
1. Extract XYZ + colour arrays from the input point cloud.
2. Load image — either from ``image_input`` (bytes / file path) or by
   rendering a synthetic front-view image from the point cloud itself.
3. Resolve / download the YOLO11n-seg checkpoint.
4. Load and cache the YOLO model (thread-safe double-checked locking).
5. Run YOLO11n-seg inference → per-instance (bbox, mask, label, confidence).
6. Back-project all 3D points into 2D using camera intrinsics.
7. Vectorised mask lookup selects which points belong to each detected instance.
8. Optionally build per-object extracted clouds and/or an annotated full cloud.

Front-view synthesis (image_input=None)
---------------------------------------
When no image is provided the handler renders a synthetic RGB image by
projecting each point's XYZ into pixel coordinates and painting its colour.
Points are painted far-to-near so the nearest point wins at each pixel.
The canvas size is derived from the principal point: W = 2·cx+1, H = 2·cy+1.
For point clouds generated by DepthEstimation the result is pixel-for-pixel
identical to the original photo because each pixel has exactly one point.

Device support
--------------
CUDA, MPS (Apple Silicon), and CPU are auto-detected via ``_torch_device()``.
AMD/ROCm surfaces as ``cuda`` through PyTorch's ROCm-compatible CUDA API,
so it is supported automatically without any extra branch.
"""

from __future__ import annotations

import io
import threading

import numpy as np
from PIL import Image

from vizion3d.core.cqrs import CommandHandler

from .commands import ObjectMaskAnnotation3DCommand
from .defaults import resolve_annotation_model_backend
from .models import MaskAnnotation3D, ObjectMaskAnnotation3DConfig, ObjectMaskAnnotation3DResult

_OBJECT_COLORS: list[list[float]] = [
    [1.0, 0.20, 0.20],
    [0.20, 1.0, 0.20],
    [0.20, 0.50, 1.0],
    [1.0, 0.90, 0.10],
    [1.0, 0.20, 1.0],
    [0.10, 1.0, 0.90],
    [1.0, 0.55, 0.10],
    [0.70, 0.10, 1.0],
    [0.10, 0.90, 0.50],
    [1.0, 0.40, 0.70],
    [0.50, 0.85, 0.20],
    [0.20, 0.50, 0.80],
]


class ObjectMaskAnnotation3DHandler(
    CommandHandler[ObjectMaskAnnotation3DCommand, ObjectMaskAnnotation3DResult]
):
    """Handles :class:`~vizion3d.annotation.commands.ObjectMaskAnnotation3DCommand`.

    YOLO11n-seg models are loaded on first use and cached in a class-level dict
    so subsequent calls within the same process reuse weights without re-reading
    disk.  A lock ensures thread-safe initialisation.
    """

    _annotation_models: dict = {}
    _model_lock = threading.Lock()

    def handle(self, command: ObjectMaskAnnotation3DCommand) -> ObjectMaskAnnotation3DResult:
        model_id = resolve_annotation_model_backend(command.model_backend)

        # Extract point cloud arrays first — needed for front-view synthesis
        # and for the back-projection step regardless of image source.
        pts, colors_orig = _extract_cloud_arrays(command.point_cloud)

        if command.image_input is None:
            # Intrinsics must be resolved before rendering (rendering requires them).
            # If any are None, derive consistent values from the cloud's angular extent.
            cfg = _derive_intrinsics_from_cloud(pts, command.advanced_config)
            image = _render_front_view(pts, colors_orig, cfg)
        elif isinstance(command.image_input, str):
            image = Image.open(command.image_input).convert("RGB")
            cfg = _resolve_intrinsics(command.advanced_config, *image.size)
        else:
            image = Image.open(io.BytesIO(command.image_input)).convert("RGB")
            cfg = _resolve_intrinsics(command.advanced_config, *image.size)

        img_w, img_h = image.size

        detections = self._run_yolo(model_id, image, cfg)
        detections = sorted(detections, key=lambda d: d[2], reverse=True)

        if not detections:
            annotated_cloud = None
            if command.return_annotated_cloud:
                import open3d as o3d

                annotated_cloud = _clone_cloud(command.point_cloud, o3d)
            return ObjectMaskAnnotation3DResult(
                annotations=[],
                annotated_cloud=annotated_cloud,
                backend_used=model_id,
            )

        in_bounds_idx, u_ib, v_ib = _backproject(pts, img_w, img_h, cfg)

        annotations: list[MaskAnnotation3D] = []
        colors_new = colors_orig.copy() if command.return_annotated_cloud else None

        for det_idx, det in enumerate(detections):
            label, class_id, confidence, bbox_2d, mask_hw = det

            in_mask = mask_hw[v_ib, u_ib]
            obj_pt_idx = in_bounds_idx[in_mask].tolist()
            obj_pt_coords = pts[obj_pt_idx].tolist()

            object_cloud = None
            if command.return_object_clouds and obj_pt_idx:
                import open3d as o3d

                object_cloud = _make_sub_cloud(pts, colors_orig, obj_pt_idx, o3d)

            if colors_new is not None and obj_pt_idx:
                col = _OBJECT_COLORS[det_idx % len(_OBJECT_COLORS)]
                colors_new[obj_pt_idx] = col

            annotations.append(
                MaskAnnotation3D(
                    label=label,
                    class_id=class_id,
                    confidence=confidence,
                    bbox_2d=bbox_2d,
                    mask_2d=mask_hw,
                    point_indices=obj_pt_idx,
                    point_coords=obj_pt_coords,
                    object_cloud=object_cloud,
                )
            )

        annotated_cloud = None
        if command.return_annotated_cloud:
            import open3d as o3d

            annotated_cloud = _make_full_cloud(pts, colors_new, o3d)

        return ObjectMaskAnnotation3DResult(
            annotations=annotations,
            annotated_cloud=annotated_cloud,
            backend_used=model_id,
        )

    # ── Model loading ─────────────────────────────────────────────────────────

    def _load_yolo(self, model_path: str):
        if model_path in self._annotation_models:
            return self._annotation_models[model_path]

        with self._model_lock:
            if model_path in self._annotation_models:
                return self._annotation_models[model_path]

            try:
                import torch
                from ultralytics import YOLO
            except ImportError as exc:
                raise ImportError(
                    "ObjectMaskAnnotation3D requires ultralytics. Run: pip install ultralytics"
                ) from exc

            device = self._torch_device(torch)
            model = YOLO(model_path)
            self._annotation_models[model_path] = (model, device)
            return self._annotation_models[model_path]

    # ── Inference ─────────────────────────────────────────────────────────────

    def _run_yolo(
        self,
        model_path: str,
        image: Image.Image,
        cfg: ObjectMaskAnnotation3DConfig,
    ) -> list[tuple[str, int, float, list[float], np.ndarray]]:
        model, device = self._load_yolo(model_path)

        results = model.predict(
            source=image,
            conf=cfg.conf_threshold,
            iou=cfg.iou_threshold,
            device=device,
            verbose=False,
            retina_masks=True,
        )

        result = results[0]

        if result.masks is None or result.boxes is None or len(result.boxes) == 0:
            return []

        boxes_xyxy = result.boxes.xyxy.cpu().numpy()
        classes = result.boxes.cls.cpu().numpy()
        confs = result.boxes.conf.cpu().numpy()
        masks_tensor = result.masks.data.cpu().numpy()  # (N, H, W) at original resolution

        detections = []
        for i in range(len(boxes_xyxy)):
            mask_hw = masks_tensor[i] > 0.5  # bool (H, W)
            detections.append(
                (
                    result.names[int(classes[i])],
                    int(classes[i]),
                    float(confs[i]),
                    boxes_xyxy[i].tolist(),
                    mask_hw,
                )
            )
        return detections

    # ── Pre-loading ───────────────────────────────────────────────────────────

    @classmethod
    def preload(cls, model_path: str) -> None:
        resolved = resolve_annotation_model_backend(model_path)
        cls()._load_yolo(resolved)

    # ── Device selection ──────────────────────────────────────────────────────

    @staticmethod
    def _torch_device(torch_module) -> str:
        if torch_module.cuda.is_available():
            return "cuda"
        if hasattr(torch_module.backends, "mps") and torch_module.backends.mps.is_available():
            return "mps"
        return "cpu"


# ── Pure helper functions ─────────────────────────────────────────────────────


def _resolve_intrinsics(
    cfg: ObjectMaskAnnotation3DConfig, img_w: int, img_h: int
) -> ObjectMaskAnnotation3DConfig:
    """Fill any None intrinsic fields from image dimensions using 0.85×width FOV heuristic."""
    fx = cfg.fx if cfg.fx is not None else img_w * 0.85
    fy = cfg.fy if cfg.fy is not None else img_w * 0.85
    cx = cfg.cx if cfg.cx is not None else img_w / 2.0
    cy = cfg.cy if cfg.cy is not None else img_h / 2.0
    return ObjectMaskAnnotation3DConfig(
        fx=fx,
        fy=fy,
        cx=cx,
        cy=cy,
        conf_threshold=cfg.conf_threshold,
        iou_threshold=cfg.iou_threshold,
    )


def _derive_intrinsics_from_cloud(
    pts: np.ndarray, cfg: ObjectMaskAnnotation3DConfig
) -> ObjectMaskAnnotation3DConfig:
    """Derive any None intrinsics from the cloud's angular extent.

    Used when no image is provided — the rendering step requires concrete intrinsic
    values, so they must be computed from the cloud geometry before rendering begins.
    Derived values are consistent with the 0.85×width heuristic: for a cloud
    generated by DepthEstimation, the recovered fx matches the original auto-derived
    value within rounding.
    """
    if all(v is not None for v in (cfg.fx, cfg.fy, cfg.cx, cfg.cy)):
        return cfg

    X, Y, Z = pts[:, 0], pts[:, 1], pts[:, 2]
    valid = Z > 0
    if not valid.any():
        return _resolve_intrinsics(cfg, 640, 480)

    ax = X[valid] / Z[valid]
    ay = Y[valid] / Z[valid]
    range_x = float(ax.max() - ax.min())

    _TARGET_W = 1024
    fx = (
        cfg.fx if cfg.fx is not None else (_TARGET_W / range_x if range_x > 0 else _TARGET_W * 0.85)
    )
    fy = cfg.fy if cfg.fy is not None else fx
    cx = cfg.cx if cfg.cx is not None else float(-ax.min() * fx)
    cy = cfg.cy if cfg.cy is not None else float(-ay.min() * fy)
    return ObjectMaskAnnotation3DConfig(
        fx=fx,
        fy=fy,
        cx=cx,
        cy=cy,
        conf_threshold=cfg.conf_threshold,
        iou_threshold=cfg.iou_threshold,
    )


def _extract_cloud_arrays(point_cloud) -> tuple[np.ndarray, np.ndarray]:
    pts = np.asarray(point_cloud.points)
    if point_cloud.has_colors():
        colors = np.asarray(point_cloud.colors).copy()
    else:
        colors = np.ones((len(pts), 3), dtype=np.float64)
    return pts, colors


def _render_front_view(
    pts: np.ndarray,
    colors: np.ndarray,
    cfg: ObjectMaskAnnotation3DConfig,
) -> Image.Image:
    """Synthesise a front-view RGB image by projecting XYZ+RGB into 2D.

    Canvas size is derived from the extent of the projected points so the
    render works correctly regardless of where the principal point sits in the
    image (e.g. stereo rigs with cx near the left edge).  Points are painted
    far-to-near so the nearest point wins at each pixel.  For DepthEstimation
    clouds (one point per pixel) the result is identical to the original photo.
    """
    X, Y, Z = pts[:, 0], pts[:, 1], pts[:, 2]
    valid = Z > 0
    if not valid.any():
        fallback_w = max(int(cfg.cx * 2) + 1, 1)
        fallback_h = max(int(cfg.cy * 2) + 1, 1)
        return Image.fromarray(np.zeros((fallback_h, fallback_w, 3), dtype=np.uint8), mode="RGB")

    u = np.round(cfg.fx * X[valid] / Z[valid] + cfg.cx).astype(np.int32)
    v = np.round(cfg.fy * Y[valid] / Z[valid] + cfg.cy).astype(np.int32)

    # Canvas spans from 0 to the maximum projected coordinate so the image
    # covers the full scene regardless of where cx/cy sits.  Points with
    # negative projected coordinates (behind or to the left of u=0) are
    # outside the image and excluded — consistent with _backproject.
    img_w = max(int(u.max()) + 1, 1)
    img_h = max(int(v.max()) + 1, 1)
    canvas = np.zeros((img_h, img_w, 3), dtype=np.uint8)

    in_bounds = (u >= 0) & (u < img_w) & (v >= 0) & (v < img_h)
    u, v = u[in_bounds], v[in_bounds]
    z_vals = Z[valid][in_bounds]
    rgb = (colors[valid][in_bounds] * 255).astype(np.uint8)

    # Far-to-near: paint furthest first so nearest point wins
    order = np.argsort(z_vals)[::-1]
    canvas[v[order], u[order]] = rgb[order]

    return Image.fromarray(canvas, mode="RGB")


def _backproject(
    pts: np.ndarray,
    img_w: int,
    img_h: int,
    cfg: ObjectMaskAnnotation3DConfig,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    X, Y, Z = pts[:, 0], pts[:, 1], pts[:, 2]
    valid = Z > 0

    u_all = np.full(len(pts), -1, dtype=np.int32)
    v_all = np.full(len(pts), -1, dtype=np.int32)

    u_proj = np.round(cfg.fx * X[valid] / Z[valid] + cfg.cx).astype(np.int32)
    v_proj = np.round(cfg.fy * Y[valid] / Z[valid] + cfg.cy).astype(np.int32)

    u_all[valid] = u_proj
    v_all[valid] = v_proj

    in_bounds = valid & (u_all >= 0) & (u_all < img_w) & (v_all >= 0) & (v_all < img_h)

    in_bounds_idx = np.where(in_bounds)[0]
    return in_bounds_idx, u_all[in_bounds_idx], v_all[in_bounds_idx]


def _make_sub_cloud(pts: np.ndarray, colors: np.ndarray, indices: list[int], o3d):
    sub_pts = pts[indices]
    sub_cols = colors[indices]
    pcd = o3d.geometry.PointCloud()
    pcd.points = o3d.utility.Vector3dVector(sub_pts)
    pcd.colors = o3d.utility.Vector3dVector(sub_cols)
    return pcd


def _make_full_cloud(pts: np.ndarray, colors: np.ndarray, o3d):
    pcd = o3d.geometry.PointCloud()
    pcd.points = o3d.utility.Vector3dVector(pts)
    pcd.colors = o3d.utility.Vector3dVector(colors)
    return pcd


def _clone_cloud(point_cloud, o3d):
    pts = np.asarray(point_cloud.points).copy()
    cols = (
        np.asarray(point_cloud.colors).copy()
        if point_cloud.has_colors()
        else np.ones((len(pts), 3))
    )
    pcd = o3d.geometry.PointCloud()
    pcd.points = o3d.utility.Vector3dVector(pts)
    pcd.colors = o3d.utility.Vector3dVector(cols)
    return pcd
