# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vision3d/proto/reconstruction.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'vision3d/proto/reconstruction.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#vision3d/proto/reconstruction.proto\x12\x17vision3d.reconstruction\"3\n\nImageInput\x12\x10\n\x08image_id\x18\x01 \x01(\t\x12\x13\n\x0bimage_bytes\x18\x02 \x01(\x0c\"X\n\nSfMRequest\x12\x33\n\x06images\x18\x01 \x03(\x0b\x32#.vision3d.reconstruction.ImageInput\x12\x15\n\rmodel_backend\x18\x02 \x01(\t\"K\n\x07Point3D\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x12\t\n\x01r\x18\x04 \x01(\x05\x12\t\n\x01g\x18\x05 \x01(\x05\x12\t\n\x01\x62\x18\x06 \x01(\x05\"v\n\nCameraPose\x12\x10\n\x08image_id\x18\x01 \x01(\t\x12:\n\x0frotation_matrix\x18\x02 \x03(\x0b\x32!.vision3d.reconstruction.FloatRow\x12\x1a\n\x12translation_vector\x18\x03 \x03(\x02\"\x1a\n\x08\x46loatRow\x12\x0e\n\x06values\x18\x01 \x03(\x02\"\x9c\x01\n\x0bSfMResponse\x12<\n\x12sparse_point_cloud\x18\x01 \x03(\x0b\x32 .vision3d.reconstruction.Point3D\x12\x39\n\x0c\x63\x61mera_poses\x18\x02 \x03(\x0b\x32#.vision3d.reconstruction.CameraPose\x12\x14\n\x0c\x62\x61\x63kend_used\x18\x03 \x01(\t2l\n\x15ReconstructionService\x12S\n\x06RunSfM\x12#.vision3d.reconstruction.SfMRequest\x1a$.vision3d.reconstruction.SfMResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vision3d.proto.reconstruction_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEINPUT']._serialized_start=64
  _globals['_IMAGEINPUT']._serialized_end=115
  _globals['_SFMREQUEST']._serialized_start=117
  _globals['_SFMREQUEST']._serialized_end=205
  _globals['_POINT3D']._serialized_start=207
  _globals['_POINT3D']._serialized_end=282
  _globals['_CAMERAPOSE']._serialized_start=284
  _globals['_CAMERAPOSE']._serialized_end=402
  _globals['_FLOATROW']._serialized_start=404
  _globals['_FLOATROW']._serialized_end=430
  _globals['_SFMRESPONSE']._serialized_start=433
  _globals['_SFMRESPONSE']._serialized_end=589
  _globals['_RECONSTRUCTIONSERVICE']._serialized_start=591
  _globals['_RECONSTRUCTIONSERVICE']._serialized_end=699
# @@protoc_insertion_point(module_scope)
