# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from vision3d.proto import reconstruction_pb2 as vision3d_dot_proto_dot_reconstruction__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vision3d/proto/reconstruction_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReconstructionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunSfM = channel.unary_unary(
                '/vision3d.reconstruction.ReconstructionService/RunSfM',
                request_serializer=vision3d_dot_proto_dot_reconstruction__pb2.SfMRequest.SerializeToString,
                response_deserializer=vision3d_dot_proto_dot_reconstruction__pb2.SfMResponse.FromString,
                _registered_method=True)


class ReconstructionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunSfM(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReconstructionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunSfM': grpc.unary_unary_rpc_method_handler(
                    servicer.RunSfM,
                    request_deserializer=vision3d_dot_proto_dot_reconstruction__pb2.SfMRequest.FromString,
                    response_serializer=vision3d_dot_proto_dot_reconstruction__pb2.SfMResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vision3d.reconstruction.ReconstructionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vision3d.reconstruction.ReconstructionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReconstructionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunSfM(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vision3d.reconstruction.ReconstructionService/RunSfM',
            vision3d_dot_proto_dot_reconstruction__pb2.SfMRequest.SerializeToString,
            vision3d_dot_proto_dot_reconstruction__pb2.SfMResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
