# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lifting.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'lifting.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rlifting.proto\x12\x10vizion3d.lifting\"\xd2\x01\n\x1c\x44\x65pthEstimationAdvanceConfig\x12\x0f\n\x02\x66x\x18\x01 \x01(\x02H\x00\x88\x01\x01\x12\x0f\n\x02\x66y\x18\x02 \x01(\x02H\x01\x88\x01\x01\x12\x0f\n\x02\x63x\x18\x03 \x01(\x02H\x02\x88\x01\x01\x12\x0f\n\x02\x63y\x18\x04 \x01(\x02H\x03\x88\x01\x01\x12\x18\n\x0b\x64\x65pth_scale\x18\x05 \x01(\x02H\x04\x88\x01\x01\x12\x18\n\x0b\x64\x65pth_trunc\x18\x06 \x01(\x02H\x05\x88\x01\x01\x42\x05\n\x03_fxB\x05\n\x03_fyB\x05\n\x03_cxB\x05\n\x03_cyB\x0e\n\x0c_depth_scaleB\x0e\n\x0c_depth_trunc\"\xa7\x02\n\x16\x44\x65pthEstimationRequest\x12\x13\n\x0bimage_bytes\x18\x01 \x01(\x0c\x12\x15\n\rmodel_backend\x18\x02 \x01(\t\x12\x1a\n\x12return_depth_image\x18\x03 \x01(\x08\x12\x1a\n\x12return_point_cloud\x18\x04 \x01(\x08\x12\x13\n\x0breturn_mesh\x18\x05 \x01(\x08\x12\x1d\n\x10local_model_path\x18\x06 \x01(\tH\x00\x88\x01\x01\x12L\n\x0f\x61\x64vanced_config\x18\x07 \x01(\x0b\x32..vizion3d.lifting.DepthEstimationAdvanceConfigH\x01\x88\x01\x01\x42\x13\n\x11_local_model_pathB\x12\n\x10_advanced_config\"\x1a\n\x08\x46loatRow\x12\x0e\n\x06values\x18\x01 \x03(\x02\"\xc4\x01\n\x17\x44\x65pthEstimationResponse\x12-\n\tdepth_map\x18\x01 \x03(\x0b\x32\x1a.vizion3d.lifting.FloatRow\x12\x11\n\tmin_depth\x18\x02 \x01(\x02\x12\x11\n\tmax_depth\x18\x03 \x01(\x02\x12\x14\n\x0c\x62\x61\x63kend_used\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65pth_image\x18\x05 \x01(\x0c\x12\x17\n\x0fpoint_cloud_ply\x18\x06 \x01(\x0c\x12\x10\n\x08mesh_ply\x18\x07 \x01(\x0c\x32{\n\x0eLiftingService\x12i\n\x12RunDepthEstimation\x12(.vizion3d.lifting.DepthEstimationRequest\x1a).vizion3d.lifting.DepthEstimationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lifting_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DEPTHESTIMATIONADVANCECONFIG']._serialized_start=36
  _globals['_DEPTHESTIMATIONADVANCECONFIG']._serialized_end=246
  _globals['_DEPTHESTIMATIONREQUEST']._serialized_start=249
  _globals['_DEPTHESTIMATIONREQUEST']._serialized_end=544
  _globals['_FLOATROW']._serialized_start=546
  _globals['_FLOATROW']._serialized_end=572
  _globals['_DEPTHESTIMATIONRESPONSE']._serialized_start=575
  _globals['_DEPTHESTIMATIONRESPONSE']._serialized_end=771
  _globals['_LIFTINGSERVICE']._serialized_start=773
  _globals['_LIFTINGSERVICE']._serialized_end=896
# @@protoc_insertion_point(module_scope)
