# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from vizion3d.proto import lifting_pb2 as vizion3d_dot_proto_dot_lifting__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vizion3d/proto/lifting_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LiftingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunDepthEstimation = channel.unary_unary(
                '/vizion3d.lifting.LiftingService/RunDepthEstimation',
                request_serializer=vizion3d_dot_proto_dot_lifting__pb2.DepthEstimationRequest.SerializeToString,
                response_deserializer=vizion3d_dot_proto_dot_lifting__pb2.DepthEstimationResponse.FromString,
                _registered_method=True)
        self.RunStereoDepth = channel.unary_unary(
                '/vizion3d.lifting.LiftingService/RunStereoDepth',
                request_serializer=vizion3d_dot_proto_dot_lifting__pb2.StereoDepthRequest.SerializeToString,
                response_deserializer=vizion3d_dot_proto_dot_lifting__pb2.StereoDepthResponse.FromString,
                _registered_method=True)
        self.RunObjectMaskAnnotation3D = channel.unary_unary(
                '/vizion3d.lifting.LiftingService/RunObjectMaskAnnotation3D',
                request_serializer=vizion3d_dot_proto_dot_lifting__pb2.ObjectMaskAnnotation3DRequest.SerializeToString,
                response_deserializer=vizion3d_dot_proto_dot_lifting__pb2.ObjectMaskAnnotation3DResponse.FromString,
                _registered_method=True)
        self.RunSceneMaskAnnotation3D = channel.unary_unary(
                '/vizion3d.lifting.LiftingService/RunSceneMaskAnnotation3D',
                request_serializer=vizion3d_dot_proto_dot_lifting__pb2.SceneMaskAnnotation3DRequest.SerializeToString,
                response_deserializer=vizion3d_dot_proto_dot_lifting__pb2.SceneMaskAnnotation3DResponse.FromString,
                _registered_method=True)
        self.RunScaleObservation = channel.unary_unary(
                '/vizion3d.lifting.LiftingService/RunScaleObservation',
                request_serializer=vizion3d_dot_proto_dot_lifting__pb2.ScaleObservationRequest.SerializeToString,
                response_deserializer=vizion3d_dot_proto_dot_lifting__pb2.ScaleObservationResponse.FromString,
                _registered_method=True)
        self.RunObject3DReconstruction = channel.unary_unary(
                '/vizion3d.lifting.LiftingService/RunObject3DReconstruction',
                request_serializer=vizion3d_dot_proto_dot_lifting__pb2.Object3DReconstructionRequest.SerializeToString,
                response_deserializer=vizion3d_dot_proto_dot_lifting__pb2.ReconstructionJobSubmission.FromString,
                _registered_method=True)
        self.GetObject3DReconstructionResult = channel.unary_unary(
                '/vizion3d.lifting.LiftingService/GetObject3DReconstructionResult',
                request_serializer=vizion3d_dot_proto_dot_lifting__pb2.ReconstructionJobResultRequest.SerializeToString,
                response_deserializer=vizion3d_dot_proto_dot_lifting__pb2.Object3DReconstructionJobResponse.FromString,
                _registered_method=True)
        self.RunSceneComponents3DReconstruction = channel.unary_unary(
                '/vizion3d.lifting.LiftingService/RunSceneComponents3DReconstruction',
                request_serializer=vizion3d_dot_proto_dot_lifting__pb2.SceneComponents3DReconstructionRequest.SerializeToString,
                response_deserializer=vizion3d_dot_proto_dot_lifting__pb2.ReconstructionJobSubmission.FromString,
                _registered_method=True)
        self.GetSceneComponents3DReconstructionResult = channel.unary_unary(
                '/vizion3d.lifting.LiftingService/GetSceneComponents3DReconstructionResult',
                request_serializer=vizion3d_dot_proto_dot_lifting__pb2.ReconstructionJobResultRequest.SerializeToString,
                response_deserializer=vizion3d_dot_proto_dot_lifting__pb2.SceneComponents3DReconstructionJobResponse.FromString,
                _registered_method=True)


class LiftingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunDepthEstimation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunStereoDepth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunObjectMaskAnnotation3D(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunSceneMaskAnnotation3D(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunScaleObservation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunObject3DReconstruction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetObject3DReconstructionResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunSceneComponents3DReconstruction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSceneComponents3DReconstructionResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LiftingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunDepthEstimation': grpc.unary_unary_rpc_method_handler(
                    servicer.RunDepthEstimation,
                    request_deserializer=vizion3d_dot_proto_dot_lifting__pb2.DepthEstimationRequest.FromString,
                    response_serializer=vizion3d_dot_proto_dot_lifting__pb2.DepthEstimationResponse.SerializeToString,
            ),
            'RunStereoDepth': grpc.unary_unary_rpc_method_handler(
                    servicer.RunStereoDepth,
                    request_deserializer=vizion3d_dot_proto_dot_lifting__pb2.StereoDepthRequest.FromString,
                    response_serializer=vizion3d_dot_proto_dot_lifting__pb2.StereoDepthResponse.SerializeToString,
            ),
            'RunObjectMaskAnnotation3D': grpc.unary_unary_rpc_method_handler(
                    servicer.RunObjectMaskAnnotation3D,
                    request_deserializer=vizion3d_dot_proto_dot_lifting__pb2.ObjectMaskAnnotation3DRequest.FromString,
                    response_serializer=vizion3d_dot_proto_dot_lifting__pb2.ObjectMaskAnnotation3DResponse.SerializeToString,
            ),
            'RunSceneMaskAnnotation3D': grpc.unary_unary_rpc_method_handler(
                    servicer.RunSceneMaskAnnotation3D,
                    request_deserializer=vizion3d_dot_proto_dot_lifting__pb2.SceneMaskAnnotation3DRequest.FromString,
                    response_serializer=vizion3d_dot_proto_dot_lifting__pb2.SceneMaskAnnotation3DResponse.SerializeToString,
            ),
            'RunScaleObservation': grpc.unary_unary_rpc_method_handler(
                    servicer.RunScaleObservation,
                    request_deserializer=vizion3d_dot_proto_dot_lifting__pb2.ScaleObservationRequest.FromString,
                    response_serializer=vizion3d_dot_proto_dot_lifting__pb2.ScaleObservationResponse.SerializeToString,
            ),
            'RunObject3DReconstruction': grpc.unary_unary_rpc_method_handler(
                    servicer.RunObject3DReconstruction,
                    request_deserializer=vizion3d_dot_proto_dot_lifting__pb2.Object3DReconstructionRequest.FromString,
                    response_serializer=vizion3d_dot_proto_dot_lifting__pb2.ReconstructionJobSubmission.SerializeToString,
            ),
            'GetObject3DReconstructionResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetObject3DReconstructionResult,
                    request_deserializer=vizion3d_dot_proto_dot_lifting__pb2.ReconstructionJobResultRequest.FromString,
                    response_serializer=vizion3d_dot_proto_dot_lifting__pb2.Object3DReconstructionJobResponse.SerializeToString,
            ),
            'RunSceneComponents3DReconstruction': grpc.unary_unary_rpc_method_handler(
                    servicer.RunSceneComponents3DReconstruction,
                    request_deserializer=vizion3d_dot_proto_dot_lifting__pb2.SceneComponents3DReconstructionRequest.FromString,
                    response_serializer=vizion3d_dot_proto_dot_lifting__pb2.ReconstructionJobSubmission.SerializeToString,
            ),
            'GetSceneComponents3DReconstructionResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSceneComponents3DReconstructionResult,
                    request_deserializer=vizion3d_dot_proto_dot_lifting__pb2.ReconstructionJobResultRequest.FromString,
                    response_serializer=vizion3d_dot_proto_dot_lifting__pb2.SceneComponents3DReconstructionJobResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vizion3d.lifting.LiftingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vizion3d.lifting.LiftingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LiftingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunDepthEstimation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vizion3d.lifting.LiftingService/RunDepthEstimation',
            vizion3d_dot_proto_dot_lifting__pb2.DepthEstimationRequest.SerializeToString,
            vizion3d_dot_proto_dot_lifting__pb2.DepthEstimationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunStereoDepth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vizion3d.lifting.LiftingService/RunStereoDepth',
            vizion3d_dot_proto_dot_lifting__pb2.StereoDepthRequest.SerializeToString,
            vizion3d_dot_proto_dot_lifting__pb2.StereoDepthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunObjectMaskAnnotation3D(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vizion3d.lifting.LiftingService/RunObjectMaskAnnotation3D',
            vizion3d_dot_proto_dot_lifting__pb2.ObjectMaskAnnotation3DRequest.SerializeToString,
            vizion3d_dot_proto_dot_lifting__pb2.ObjectMaskAnnotation3DResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunSceneMaskAnnotation3D(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vizion3d.lifting.LiftingService/RunSceneMaskAnnotation3D',
            vizion3d_dot_proto_dot_lifting__pb2.SceneMaskAnnotation3DRequest.SerializeToString,
            vizion3d_dot_proto_dot_lifting__pb2.SceneMaskAnnotation3DResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunScaleObservation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vizion3d.lifting.LiftingService/RunScaleObservation',
            vizion3d_dot_proto_dot_lifting__pb2.ScaleObservationRequest.SerializeToString,
            vizion3d_dot_proto_dot_lifting__pb2.ScaleObservationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunObject3DReconstruction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vizion3d.lifting.LiftingService/RunObject3DReconstruction',
            vizion3d_dot_proto_dot_lifting__pb2.Object3DReconstructionRequest.SerializeToString,
            vizion3d_dot_proto_dot_lifting__pb2.ReconstructionJobSubmission.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetObject3DReconstructionResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vizion3d.lifting.LiftingService/GetObject3DReconstructionResult',
            vizion3d_dot_proto_dot_lifting__pb2.ReconstructionJobResultRequest.SerializeToString,
            vizion3d_dot_proto_dot_lifting__pb2.Object3DReconstructionJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunSceneComponents3DReconstruction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vizion3d.lifting.LiftingService/RunSceneComponents3DReconstruction',
            vizion3d_dot_proto_dot_lifting__pb2.SceneComponents3DReconstructionRequest.SerializeToString,
            vizion3d_dot_proto_dot_lifting__pb2.ReconstructionJobSubmission.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSceneComponents3DReconstructionResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vizion3d.lifting.LiftingService/GetSceneComponents3DReconstructionResult',
            vizion3d_dot_proto_dot_lifting__pb2.ReconstructionJobResultRequest.SerializeToString,
            vizion3d_dot_proto_dot_lifting__pb2.SceneComponents3DReconstructionJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
